unbind C-a
set -g prefix C-Space
bind C-Space send-prefix


unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"


bind N new-window

bind y setw synchronize-panes

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R 

unbind v
unbind b

bind v split-window -v -c "#{pane_current_path}"
bind b split-window -h -c "#{pane_current_path}" 
